workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build
  - test
  - linters

build-job:
  stage: build
  tags:
    - students
  scrip:
    - docker build -t my-backend-image api/

unittest:
  stage: test
  tags:
    - students
  script:
    - docker compose -f api/docker-compose-test.yaml up -d
  after_script:
    - docker compose -f api/docker-compose-test.yaml rm -sf

wemake-python-styleguide:
  stage: linters
  tags:
    - students
  script: flake8 api
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'develop'
    - when: never

mypy:
  stage: linters
  tags:
    - students
  script:
    - mypy --disable-error-code=import-not-found api/
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'develop'
    - when: never
