workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build
  - test
  - linter

build-job:
  stage: build
  tags:
    - docker
  script:
    - docker build -t my-backend-image api/

unittest:
  stage: test
  tags:
    - docker
  script:
    - docker compose -f api/docker-compose-test.yaml up --abort-on-container-exit
  after_script:
    - docker compose -f api/docker-compose-test.yaml down --remove-orphans

wemake-python-styleguide:
  stage: linter
  tags:
    - docker
  script: docker run --rm my-backend-image bash -c "pip install wemake-python-styleguide && flake8 app/"
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'develop'
    - when: never
