services:
  backend:
    image: my-backend-image:latest
    build:
      context: ./api
    container_name: my-backend-container
    working_dir: /src
    ports:
      - "80:80"
    command: "uvicorn main:app --host 0.0.0.0 --port 80"