services:
  nginx:
    build:
      context: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dev
  backend:
    image: prod-backend-image:latest
    working_dir: /app/src
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PASS=${DB_PASS}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_NAME=${DB_NAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_URL=${S3_URL}
      - S3_BUCKET_NANE=${S3_BUCKET_NANE}
    command: "uvicorn main:app --host 0.0.0.0 --port 5555"
    restart: always
    depends_on:
      - redis
    networks:
      - dev
  redis:
    image: redis:6.2-alpine
    command: redis-server --save 20 1 --loglevel warning
    restart: always
    volumes:
      - cache:/data
    networks:
      - dev

networks:
  dev:
volumes:
  cache:
    driver: local
