services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    networks:
      - app_network

  tests:
    image: my-backend-image:latest
    build:
      context: .
    command: pytest tests -s -v -p no:warnings
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:admin@db:5432
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network: